### PR TITLE
Refactoring and cleaning README

### PR DESCRIPTION
**Pull request by cchacin**

### CODE REVIEW

**Comment by danielsoro** [comment]
@cchacin 

https://github.com/tomitribe/beryllium/blob/master/pom.xml#L28-L31
why does not use https://github.com/tomitribe/tomitribe-oss-parent ?

**Comment by cchacin** [comment]
@danielsoro I have to fix some issues before change it to the tomitribe-oss-parent, But that will be my next step.

**Comment by cchacin** [comment]
@danielsoro Do you know why the asciidoc `include` directive is not working on github?

Check it here:
https://github.com/tomitribe/beryllium/tree/readme-asciidoc

**Comment by danielsoro** [comment]
@cchacin 

No idea!

**Comment by cchacin** [comment]
Closing this for now

**Pull request closed without merging**
